config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations'
   }
  root 'top#index'
  get 'top/notice'
  resources :users, only: %i(show)
  resources :microposts,          only: [:show,:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true

  mount_uploader :picture, ImgNameUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :img_name, ImgNameUploader
  enum sex: { ç”·: 0, å¥³: 1 }

  #仮実装
  def feed
    Micropost.where("user_id = ?", id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
  #ログインしていない場合はログイン画面に遷移する。
  before_action :authenticate_user!
  #deviseコントローラが動いたら、configure_permitted_parametersを処理する。
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i(name self_introduction sex img_name))
    devise_parameter_sanitizer.permit(:account_update, keys: %i(name self_introduction sex img_name))
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :create, :destroy]
  before_action :correct_user,   only: :destroy

  def show
    if user_signed_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed
    end
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'top/index'
    end
  end

  def destroy
     @micropost.destroy
     flash[:success] = "Micropost deleted"
     redirect_to request.referrer || root_url
   end

  private

    def micropost_params
      params.require(:micropost).permit(:content, :picture)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    if user_signed_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed
    end
  end

  def notice
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
 #frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  #GET /resource/sign_up
  def new
    super
  end

  #POST /resource
  def create
    super
  end

  #GET /resource/edit
  def edit
    super
  end

  #PUT /resource
  def update
    super
  end

  #DELETE /resource
  def destroy
    super
  end

  #GET /resource/cancel
  #Forces the session data which is usually expired after sign
  #in to be expired now. This is useful if the user wants to
  #cancel oauth signing in/up in the middle of the process,
  #removing all OAuth session data.
  def cancel
    super
  end

  protected

  #If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  #If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  #The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  #The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
   def new
     super
   end

  # POST /resource/sign_in
   def create
     super
   end

  # DELETE /resource/sign_out
   def destroy
     super
   end

   protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_in_params
     devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
   end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
      @user = User.find_by(id: params[:id])
      @microposts = @user.microposts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # ページごとの完全なタイトルを返します。
  def full_title(page_title = '')
    base_title = "Instagram Clone"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "flash flash__#{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
      <%= link_to "トップページ",   root_path %></li>
  </small>
  <nav>
    <ul>
      <li><%= link_to "画像投稿アップロード", micropost_path(current_user), class: "btn btn-lg btn-primary" if user_signed_in? %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to image_tag("logo.png"), root_path %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><form><input type="text" onfocus="placeholders()" value="キーワードを入力" id="placeholder" /></form></li>
              <li><%= link_to "通知",   top_notice_path %></li>
              <li><%= link_to "プロフィール", user_path(current_user.id) %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_rails_default.html.erb
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1" >
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/flash' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%#= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <% if !micropost.user.img_name.nil? %>
    <%= image_tag  micropost.user.img_name ,size: 50 %>
    <% else %>
    <%= link_to image_tag("app/assets/images/rails.png", alt: "Rails logo", size: 50) %>
  <% end %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <%= image_tag micropost.picture.url if micropost.picture? %>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user == micropost.user %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/microposts/show.html.erb
<%= form_for(@micropost) do |f| %>
  <%#= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <div class="form-group">
    画像:
    <%= f.file_field :picture %>
  </div>
  <%= f.submit "投稿", class: "btn btn-primary" %>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%#= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<div class='userInfo'>
  <div class='userInfo_img'>
    <%= image_tag current_user.img_name %>
  </div>
  <div class='userInfo_name'><%= link_to current_user.name, current_user %></div>
  <div class='userInfo_microcount'><%= pluralize(current_user.microposts.count, "micropost") %></div>
</div>

app/views/top/index.html.erb
<div class="loginPage">
  <div class="container">
      <%= render 'shared/user_info' %>
      <div class="col-md-8">
        <%= render 'shared/feed' %>
      </div>
      <%#= link_to "メールアドレスでログインする", new_user_session_path,
            class: "btn loginPage_contents_btn" %>
  </div>
</div>

app/views/top/notice.html.erb
<h1>通知ページ（仮）</h1>

app/views/users/show.html.erb
<div class='usershowPage'>
  <div class='container'>
    <div class='userInfo'>
      <div class='userInfo_img'>
        <%= image_tag @user.img_name %>
      </div>
      <div class='userInfo_name'><%= @user.name%></div>
      <div class='userInfo_selfIntroduction'><%= @user.self_introduction %></div>
    </div>
    <% if current_user.id == @user.id %>
      <div class='userAction'>
        <div class="userAction_edit userAction_common">
          <%= link_to(content_tag(:i, "", class: 'fas fa-edit fa-2x'), edit_user_registration_path) %>
          <span>情報を編集</span>
        </div>
        <div class='userAction_logout userAction_common'>
          <%= link_to(content_tag(:i, "", class: 'fas fa-cog fa-2x'), destroy_user_session_path, method: :delete) %>
          <span>ログアウト</span>
        </div>
      </div>
    <% end %>
    <div class="col-md-8">
      <% if @user.microposts.any? %>
        <ol class="microposts">
          <%= render @microposts %>
        </ol>
      <% end %>
    </div>
  </div>
</div>